name: doover_project_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: MuseoRegular
      fonts:
        - asset: assets/fonts/MuseoSansCyrl_0.otf

    - family: Museo500
      fonts:
        - asset: assets/fonts/MuseoSansCyrl_1.otf

    - family: MuseoBold
      fonts:
        - asset: assets/fonts/MuseoSansCyrl_2.otf
